[build]
  base = "website/"
  command = "npm run build"
  publish = "out/"

[build.environment]
  NEXT_PUBLIC_BASE_PATH = ""
  NEXT_PUBLIC_SITE_URL = "https://esp-home.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
